makeblastdb -in EPI_fasta/promoter12700.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5732.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10518.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3218.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3221.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19504.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18111.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12601.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8130.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8139.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15302.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20353.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10882.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10313.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16642.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16644.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15438.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19461.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8131.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6115.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20351.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11047.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15307.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11054.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17636.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3680.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20377.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4108.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8917.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6540.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6541.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19503.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14701.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8942.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8937.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5674.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11058.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12465.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15397.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11049.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4091.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19826.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8133.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6117.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8132.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17589.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19309.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10278.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11772.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7047.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7174.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15305.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15993.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10133.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19501.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2124.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11048.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17481.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7035.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3524.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5728.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19467.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4102.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15439.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18288.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19121.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18291.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15432.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15402.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10400.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter21030.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15006.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10821.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2128.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15399.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12466.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6420.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7038.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17250.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19968.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16641.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4860.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12699.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6384.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter21031.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2256.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10883.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9609.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7023.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17426.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4832.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19002.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9532.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13232.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2264.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11046.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6113.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19310.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19468.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20896.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20919.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11329.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14708.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4104.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12693.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19465.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14702.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13235.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19001.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17038.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19889.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3206.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6539.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16639.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13855.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17427.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18294.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19460.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17496.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8935.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10824.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6383.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4092.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20350.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7025.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4107.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7104.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11052.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19064.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9139.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3344.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17486.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11333.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3433.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2263.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19827.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12035.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14704.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16638.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15401.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5280.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12464.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6417.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7173.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15306.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20459.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20900.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10279.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8692.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1549.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17432.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16591.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10823.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7046.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18293.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17638.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3219.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5936.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16625.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11332.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17040.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4110.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6554.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12695.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11062.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3267.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10132.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18296.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19003.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14700.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20362.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10520.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8141.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6118.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20355.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4861.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17487.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16589.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7169.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14707.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19295.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18106.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11645.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4866.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20364.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12696.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20352.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12954.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3446.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter21032.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12694.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20897.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17429.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3268.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6557.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter39.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17036.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3266.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6558.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16643.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7171.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8143.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13229.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2265.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8004.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17494.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2123.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3509.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12032.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19469.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6555.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8934.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15996.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7491.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8135.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18534.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6419.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18285.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3683.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1552.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8943.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13230.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20379.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20378.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1338.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12702.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18287.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19500.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8938.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15999.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18289.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20899.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19311.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11055.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17485.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3222.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8124.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4865.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3434.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20349.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11775.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17041.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10134.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7022.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6387.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19967.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15005.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5281.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12602.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19966.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5731.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19965.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4792.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11774.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1553.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18110.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4791.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16593.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6553.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7105.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3341.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19502.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11057.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1025.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13854.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19062.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18084.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12467.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5730.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15411.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3525.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11328.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2266.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8082.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2126.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20358.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15303.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10519.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8941.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18870.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13853.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19470.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19887.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10135.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18109.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19466.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8138.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3684.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3345.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2994.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2789.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12703.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20356.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7170.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3681.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19828.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8142.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12692.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6538.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10822.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16637.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18086.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8005.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11330.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19119.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter38.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4837.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1026.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2839.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20359.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8140.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6552.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4867.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11060.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16590.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1866.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11778.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14710.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4863.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11051.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17482.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12033.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7048.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12698.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15430.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20898.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15004.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20354.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4106.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4941.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17591.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18083.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12468.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1548.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6418.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15308.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10399.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12031.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2259.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20376.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5727.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19463.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18295.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6116.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter241.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1554.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4944.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17037.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter36.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3692.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19464.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16305.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3205.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12697.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7039.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15994.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3447.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18533.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8134.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15410.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18089.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8137.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8136.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15997.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5277.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1864.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter40.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18087.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17497.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5278.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11059.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8081.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14705.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1547.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19063.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5279.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18869.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13231.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16304.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11777.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19312.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12034.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter37.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16592.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18532.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15403.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20361.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6551.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6119.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7024.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4089.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8936.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2125.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17428.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14706.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15400.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8944.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4945.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1550.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19964.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18088.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11061.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13225.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1551.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15300.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter245.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5275.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18535.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17495.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8945.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8916.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18108.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15998.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15995.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8933.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20360.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17498.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20357.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2262.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4943.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3445.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16816.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18085.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4947.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10150.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19120.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1546.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11327.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16640.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18292.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19122.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9138.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12036.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19890.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2267.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18284.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12469.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9531.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3203.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12470.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11053.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5276.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1865.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7037.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3682.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11773.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4105.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6386.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12701.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter242.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16380.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10131.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13228.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15299.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4090.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17431.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15398.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13233.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18290.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter35.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19888.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3435.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17588.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3204.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16014.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11646.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4109.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17483.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11776.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20363.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4948.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15431.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2260.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17039.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8123.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7021.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3220.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter8691.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2261.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6114.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter5729.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13226.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13227.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7167.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14703.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17590.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18286.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter18107.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter20380.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16817.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter19462.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7103.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2127.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter243.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15301.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4862.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17430.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6385.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16303.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4864.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10401.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter15304.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17637.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4103.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter2258.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter6556.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter13234.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11056.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter3223.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17425.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7106.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter240.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4845.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter1863.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter14709.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11050.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter17484.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter16883.fa -dbtype nucl >> EPI_makedb.log
