blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter35.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter36.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter37.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter38.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter39.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter40.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer6.fa -db EPI_fasta/promoter240.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer6.fa -db EPI_fasta/promoter241.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer6.fa -db EPI_fasta/promoter242.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer6.fa -db EPI_fasta/promoter243.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer6.fa -db EPI_fasta/promoter245.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter240.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter241.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter242.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter243.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter245.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer8.fa -db EPI_fasta/promoter240.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer8.fa -db EPI_fasta/promoter241.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer8.fa -db EPI_fasta/promoter242.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer8.fa -db EPI_fasta/promoter243.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer8.fa -db EPI_fasta/promoter245.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer9.fa -db EPI_fasta/promoter240.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer9.fa -db EPI_fasta/promoter241.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer9.fa -db EPI_fasta/promoter242.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer9.fa -db EPI_fasta/promoter243.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer9.fa -db EPI_fasta/promoter245.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer20.fa -db EPI_fasta/promoter1025.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer20.fa -db EPI_fasta/promoter1026.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer26.fa -db EPI_fasta/promoter1338.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer27.fa -db EPI_fasta/promoter1338.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer40.fa -db EPI_fasta/promoter1546.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer40.fa -db EPI_fasta/promoter1547.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer40.fa -db EPI_fasta/promoter1548.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer40.fa -db EPI_fasta/promoter1549.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer40.fa -db EPI_fasta/promoter1550.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer40.fa -db EPI_fasta/promoter1551.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer40.fa -db EPI_fasta/promoter1552.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer40.fa -db EPI_fasta/promoter1553.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer40.fa -db EPI_fasta/promoter1554.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer45.fa -db EPI_fasta/promoter1863.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer46.fa -db EPI_fasta/promoter1864.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer46.fa -db EPI_fasta/promoter1865.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer46.fa -db EPI_fasta/promoter1866.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer56.fa -db EPI_fasta/promoter2123.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer56.fa -db EPI_fasta/promoter2124.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer56.fa -db EPI_fasta/promoter2125.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer56.fa -db EPI_fasta/promoter2126.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer56.fa -db EPI_fasta/promoter2127.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer56.fa -db EPI_fasta/promoter2128.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2256.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2258.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2259.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2260.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2261.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2262.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2263.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2264.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2265.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2266.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer57.fa -db EPI_fasta/promoter2267.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2256.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2258.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2259.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2260.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2261.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2262.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2263.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2264.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2265.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2266.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer58.fa -db EPI_fasta/promoter2267.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer71.fa -db EPI_fasta/promoter2789.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer76.fa -db EPI_fasta/promoter2839.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer84.fa -db EPI_fasta/promoter2994.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer96.fa -db EPI_fasta/promoter3203.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer96.fa -db EPI_fasta/promoter3204.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer96.fa -db EPI_fasta/promoter3205.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer96.fa -db EPI_fasta/promoter3206.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer97.fa -db EPI_fasta/promoter3203.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer97.fa -db EPI_fasta/promoter3205.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer97.fa -db EPI_fasta/promoter3206.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer99.fa -db EPI_fasta/promoter3218.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer99.fa -db EPI_fasta/promoter3219.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer99.fa -db EPI_fasta/promoter3220.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer99.fa -db EPI_fasta/promoter3221.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer99.fa -db EPI_fasta/promoter3222.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer99.fa -db EPI_fasta/promoter3223.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer100.fa -db EPI_fasta/promoter3218.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer100.fa -db EPI_fasta/promoter3219.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer100.fa -db EPI_fasta/promoter3220.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer100.fa -db EPI_fasta/promoter3221.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer100.fa -db EPI_fasta/promoter3222.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer100.fa -db EPI_fasta/promoter3223.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer103.fa -db EPI_fasta/promoter3266.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer103.fa -db EPI_fasta/promoter3267.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer103.fa -db EPI_fasta/promoter3268.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer104.fa -db EPI_fasta/promoter3266.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer104.fa -db EPI_fasta/promoter3267.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer104.fa -db EPI_fasta/promoter3268.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer106.fa -db EPI_fasta/promoter3341.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer107.fa -db EPI_fasta/promoter3344.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer107.fa -db EPI_fasta/promoter3345.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer108.fa -db EPI_fasta/promoter3344.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer108.fa -db EPI_fasta/promoter3345.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer109.fa -db EPI_fasta/promoter3344.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer109.fa -db EPI_fasta/promoter3345.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer110.fa -db EPI_fasta/promoter3344.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer110.fa -db EPI_fasta/promoter3345.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer111.fa -db EPI_fasta/promoter3344.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer111.fa -db EPI_fasta/promoter3345.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer112.fa -db EPI_fasta/promoter3433.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer112.fa -db EPI_fasta/promoter3434.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer112.fa -db EPI_fasta/promoter3435.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer113.fa -db EPI_fasta/promoter3433.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer113.fa -db EPI_fasta/promoter3434.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer113.fa -db EPI_fasta/promoter3435.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer114.fa -db EPI_fasta/promoter3433.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer114.fa -db EPI_fasta/promoter3434.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer114.fa -db EPI_fasta/promoter3435.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer115.fa -db EPI_fasta/promoter3433.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer115.fa -db EPI_fasta/promoter3434.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer115.fa -db EPI_fasta/promoter3435.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer116.fa -db EPI_fasta/promoter3433.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer116.fa -db EPI_fasta/promoter3434.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer116.fa -db EPI_fasta/promoter3435.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer117.fa -db EPI_fasta/promoter3445.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer117.fa -db EPI_fasta/promoter3446.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer117.fa -db EPI_fasta/promoter3447.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer118.fa -db EPI_fasta/promoter3509.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer120.fa -db EPI_fasta/promoter3524.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer120.fa -db EPI_fasta/promoter3525.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer126.fa -db EPI_fasta/promoter3680.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer126.fa -db EPI_fasta/promoter3681.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer126.fa -db EPI_fasta/promoter3682.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer126.fa -db EPI_fasta/promoter3683.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer126.fa -db EPI_fasta/promoter3684.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer127.fa -db EPI_fasta/promoter3680.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer127.fa -db EPI_fasta/promoter3681.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer127.fa -db EPI_fasta/promoter3682.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer127.fa -db EPI_fasta/promoter3683.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer127.fa -db EPI_fasta/promoter3684.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer128.fa -db EPI_fasta/promoter3692.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer136.fa -db EPI_fasta/promoter4089.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer136.fa -db EPI_fasta/promoter4090.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer136.fa -db EPI_fasta/promoter4091.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer136.fa -db EPI_fasta/promoter4092.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer137.fa -db EPI_fasta/promoter4102.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer137.fa -db EPI_fasta/promoter4103.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer137.fa -db EPI_fasta/promoter4104.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer137.fa -db EPI_fasta/promoter4105.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer137.fa -db EPI_fasta/promoter4106.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer137.fa -db EPI_fasta/promoter4107.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer137.fa -db EPI_fasta/promoter4108.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer137.fa -db EPI_fasta/promoter4109.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer137.fa -db EPI_fasta/promoter4110.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer156.fa -db EPI_fasta/promoter6383.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer156.fa -db EPI_fasta/promoter6384.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer156.fa -db EPI_fasta/promoter6385.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer156.fa -db EPI_fasta/promoter6386.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer156.fa -db EPI_fasta/promoter6387.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer157.fa -db EPI_fasta/promoter6417.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer157.fa -db EPI_fasta/promoter6418.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer157.fa -db EPI_fasta/promoter6419.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer157.fa -db EPI_fasta/promoter6420.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer169.fa -db EPI_fasta/promoter6538.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer169.fa -db EPI_fasta/promoter6539.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer169.fa -db EPI_fasta/promoter6540.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer169.fa -db EPI_fasta/promoter6541.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer170.fa -db EPI_fasta/promoter6538.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer170.fa -db EPI_fasta/promoter6539.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer170.fa -db EPI_fasta/promoter6540.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer170.fa -db EPI_fasta/promoter6541.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer171.fa -db EPI_fasta/promoter6538.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer171.fa -db EPI_fasta/promoter6539.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer171.fa -db EPI_fasta/promoter6540.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer171.fa -db EPI_fasta/promoter6541.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer173.fa -db EPI_fasta/promoter6551.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer173.fa -db EPI_fasta/promoter6552.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer173.fa -db EPI_fasta/promoter6553.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer173.fa -db EPI_fasta/promoter6554.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer173.fa -db EPI_fasta/promoter6555.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer173.fa -db EPI_fasta/promoter6556.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer173.fa -db EPI_fasta/promoter6557.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer173.fa -db EPI_fasta/promoter6558.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer174.fa -db EPI_fasta/promoter6551.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer174.fa -db EPI_fasta/promoter6552.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer174.fa -db EPI_fasta/promoter6553.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer174.fa -db EPI_fasta/promoter6554.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer174.fa -db EPI_fasta/promoter6555.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer174.fa -db EPI_fasta/promoter6556.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer174.fa -db EPI_fasta/promoter6557.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer174.fa -db EPI_fasta/promoter6558.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer175.fa -db EPI_fasta/promoter6551.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer175.fa -db EPI_fasta/promoter6552.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer175.fa -db EPI_fasta/promoter6553.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer175.fa -db EPI_fasta/promoter6554.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer175.fa -db EPI_fasta/promoter6555.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer175.fa -db EPI_fasta/promoter6556.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer175.fa -db EPI_fasta/promoter6557.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer175.fa -db EPI_fasta/promoter6558.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer176.fa -db EPI_fasta/promoter6551.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer176.fa -db EPI_fasta/promoter6552.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer176.fa -db EPI_fasta/promoter6553.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer176.fa -db EPI_fasta/promoter6554.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer176.fa -db EPI_fasta/promoter6555.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer176.fa -db EPI_fasta/promoter6556.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer176.fa -db EPI_fasta/promoter6557.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer176.fa -db EPI_fasta/promoter6558.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer177.fa -db EPI_fasta/promoter6551.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer177.fa -db EPI_fasta/promoter6552.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer177.fa -db EPI_fasta/promoter6553.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer177.fa -db EPI_fasta/promoter6554.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer177.fa -db EPI_fasta/promoter6555.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer177.fa -db EPI_fasta/promoter6556.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer177.fa -db EPI_fasta/promoter6557.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer177.fa -db EPI_fasta/promoter6558.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer178.fa -db EPI_fasta/promoter6551.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer178.fa -db EPI_fasta/promoter6552.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer178.fa -db EPI_fasta/promoter6553.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer178.fa -db EPI_fasta/promoter6554.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer178.fa -db EPI_fasta/promoter6555.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer178.fa -db EPI_fasta/promoter6556.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer178.fa -db EPI_fasta/promoter6557.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer178.fa -db EPI_fasta/promoter6558.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer179.fa -db EPI_fasta/promoter6551.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer179.fa -db EPI_fasta/promoter6552.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer179.fa -db EPI_fasta/promoter6553.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer179.fa -db EPI_fasta/promoter6554.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer179.fa -db EPI_fasta/promoter6555.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer179.fa -db EPI_fasta/promoter6556.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer179.fa -db EPI_fasta/promoter6557.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer179.fa -db EPI_fasta/promoter6558.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer188.fa -db EPI_fasta/promoter7021.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer188.fa -db EPI_fasta/promoter7022.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer188.fa -db EPI_fasta/promoter7023.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer188.fa -db EPI_fasta/promoter7024.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer188.fa -db EPI_fasta/promoter7025.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer189.fa -db EPI_fasta/promoter7021.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer189.fa -db EPI_fasta/promoter7022.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer189.fa -db EPI_fasta/promoter7023.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer189.fa -db EPI_fasta/promoter7024.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer189.fa -db EPI_fasta/promoter7025.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer190.fa -db EPI_fasta/promoter7035.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer190.fa -db EPI_fasta/promoter7037.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer190.fa -db EPI_fasta/promoter7038.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer190.fa -db EPI_fasta/promoter7039.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer191.fa -db EPI_fasta/promoter7035.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer191.fa -db EPI_fasta/promoter7037.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer191.fa -db EPI_fasta/promoter7038.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer191.fa -db EPI_fasta/promoter7039.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer192.fa -db EPI_fasta/promoter7046.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer192.fa -db EPI_fasta/promoter7047.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer192.fa -db EPI_fasta/promoter7048.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer193.fa -db EPI_fasta/promoter7046.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer193.fa -db EPI_fasta/promoter7047.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer193.fa -db EPI_fasta/promoter7048.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer197.fa -db EPI_fasta/promoter7103.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer197.fa -db EPI_fasta/promoter7104.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer197.fa -db EPI_fasta/promoter7105.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer197.fa -db EPI_fasta/promoter7106.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer200.fa -db EPI_fasta/promoter7167.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer200.fa -db EPI_fasta/promoter7169.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer200.fa -db EPI_fasta/promoter7170.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer200.fa -db EPI_fasta/promoter7171.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer200.fa -db EPI_fasta/promoter7173.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer200.fa -db EPI_fasta/promoter7174.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer211.fa -db EPI_fasta/promoter7491.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer226.fa -db EPI_fasta/promoter4791.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer226.fa -db EPI_fasta/promoter4792.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer230.fa -db EPI_fasta/promoter4832.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer231.fa -db EPI_fasta/promoter4837.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer232.fa -db EPI_fasta/promoter4837.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer233.fa -db EPI_fasta/promoter4845.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer234.fa -db EPI_fasta/promoter4860.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer234.fa -db EPI_fasta/promoter4861.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer234.fa -db EPI_fasta/promoter4862.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer234.fa -db EPI_fasta/promoter4863.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer234.fa -db EPI_fasta/promoter4864.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer234.fa -db EPI_fasta/promoter4865.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer234.fa -db EPI_fasta/promoter4866.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer234.fa -db EPI_fasta/promoter4867.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer237.fa -db EPI_fasta/promoter4941.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer237.fa -db EPI_fasta/promoter4943.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer237.fa -db EPI_fasta/promoter4944.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer237.fa -db EPI_fasta/promoter4945.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer238.fa -db EPI_fasta/promoter4947.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer238.fa -db EPI_fasta/promoter4948.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer240.fa -db EPI_fasta/promoter5275.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer240.fa -db EPI_fasta/promoter5276.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer240.fa -db EPI_fasta/promoter5277.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer240.fa -db EPI_fasta/promoter5278.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer240.fa -db EPI_fasta/promoter5279.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer240.fa -db EPI_fasta/promoter5280.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer240.fa -db EPI_fasta/promoter5281.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer241.fa -db EPI_fasta/promoter5275.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer241.fa -db EPI_fasta/promoter5276.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer241.fa -db EPI_fasta/promoter5277.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer241.fa -db EPI_fasta/promoter5278.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer241.fa -db EPI_fasta/promoter5279.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer241.fa -db EPI_fasta/promoter5281.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer250.fa -db EPI_fasta/promoter5674.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer253.fa -db EPI_fasta/promoter5727.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer253.fa -db EPI_fasta/promoter5728.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer253.fa -db EPI_fasta/promoter5729.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer253.fa -db EPI_fasta/promoter5730.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer253.fa -db EPI_fasta/promoter5731.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer253.fa -db EPI_fasta/promoter5732.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer254.fa -db EPI_fasta/promoter5727.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer254.fa -db EPI_fasta/promoter5728.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer254.fa -db EPI_fasta/promoter5729.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer254.fa -db EPI_fasta/promoter5730.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer254.fa -db EPI_fasta/promoter5731.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer254.fa -db EPI_fasta/promoter5732.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer263.fa -db EPI_fasta/promoter5936.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer264.fa -db EPI_fasta/promoter5936.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer272.fa -db EPI_fasta/promoter6113.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer272.fa -db EPI_fasta/promoter6114.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer272.fa -db EPI_fasta/promoter6115.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer272.fa -db EPI_fasta/promoter6116.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer272.fa -db EPI_fasta/promoter6117.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer272.fa -db EPI_fasta/promoter6118.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer272.fa -db EPI_fasta/promoter6119.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer297.fa -db EPI_fasta/promoter8004.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer297.fa -db EPI_fasta/promoter8005.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer298.fa -db EPI_fasta/promoter8081.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer298.fa -db EPI_fasta/promoter8082.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer299.fa -db EPI_fasta/promoter8081.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer299.fa -db EPI_fasta/promoter8082.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer302.fa -db EPI_fasta/promoter8123.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer302.fa -db EPI_fasta/promoter8124.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8130.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8131.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8132.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8133.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8134.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8135.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8136.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8137.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8138.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8139.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8140.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8141.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8142.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer303.fa -db EPI_fasta/promoter8143.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer316.fa -db EPI_fasta/promoter8691.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer316.fa -db EPI_fasta/promoter8692.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer323.fa -db EPI_fasta/promoter8916.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer323.fa -db EPI_fasta/promoter8917.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer324.fa -db EPI_fasta/promoter8916.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer324.fa -db EPI_fasta/promoter8917.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer326.fa -db EPI_fasta/promoter8933.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer326.fa -db EPI_fasta/promoter8934.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer326.fa -db EPI_fasta/promoter8935.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer326.fa -db EPI_fasta/promoter8936.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer326.fa -db EPI_fasta/promoter8937.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer326.fa -db EPI_fasta/promoter8938.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer327.fa -db EPI_fasta/promoter8941.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer327.fa -db EPI_fasta/promoter8942.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer327.fa -db EPI_fasta/promoter8943.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer327.fa -db EPI_fasta/promoter8944.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer327.fa -db EPI_fasta/promoter8945.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer332.fa -db EPI_fasta/promoter9138.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer332.fa -db EPI_fasta/promoter9139.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer353.fa -db EPI_fasta/promoter9531.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer353.fa -db EPI_fasta/promoter9532.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer357.fa -db EPI_fasta/promoter9609.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer376.fa -db EPI_fasta/promoter10131.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer376.fa -db EPI_fasta/promoter10132.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer376.fa -db EPI_fasta/promoter10133.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer376.fa -db EPI_fasta/promoter10134.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer376.fa -db EPI_fasta/promoter10135.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer377.fa -db EPI_fasta/promoter10131.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer377.fa -db EPI_fasta/promoter10132.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer377.fa -db EPI_fasta/promoter10133.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer377.fa -db EPI_fasta/promoter10134.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer377.fa -db EPI_fasta/promoter10135.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer378.fa -db EPI_fasta/promoter10150.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer382.fa -db EPI_fasta/promoter10278.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer382.fa -db EPI_fasta/promoter10279.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer383.fa -db EPI_fasta/promoter10313.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer386.fa -db EPI_fasta/promoter10399.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer386.fa -db EPI_fasta/promoter10400.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer386.fa -db EPI_fasta/promoter10401.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer392.fa -db EPI_fasta/promoter10518.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer392.fa -db EPI_fasta/promoter10519.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer392.fa -db EPI_fasta/promoter10520.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer393.fa -db EPI_fasta/promoter10518.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer393.fa -db EPI_fasta/promoter10519.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer393.fa -db EPI_fasta/promoter10520.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer394.fa -db EPI_fasta/promoter10518.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer394.fa -db EPI_fasta/promoter10519.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer394.fa -db EPI_fasta/promoter10520.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer410.fa -db EPI_fasta/promoter10821.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer410.fa -db EPI_fasta/promoter10822.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer410.fa -db EPI_fasta/promoter10823.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer410.fa -db EPI_fasta/promoter10824.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer413.fa -db EPI_fasta/promoter10882.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer413.fa -db EPI_fasta/promoter10883.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer414.fa -db EPI_fasta/promoter10882.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer414.fa -db EPI_fasta/promoter10883.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11046.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11047.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11048.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11049.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11050.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11051.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11052.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11053.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11054.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11055.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11056.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11057.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11058.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11059.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11060.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11061.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer424.fa -db EPI_fasta/promoter11062.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer428.fa -db EPI_fasta/promoter11327.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer428.fa -db EPI_fasta/promoter11328.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer428.fa -db EPI_fasta/promoter11329.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer428.fa -db EPI_fasta/promoter11330.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer429.fa -db EPI_fasta/promoter11332.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer429.fa -db EPI_fasta/promoter11333.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer434.fa -db EPI_fasta/promoter11645.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer434.fa -db EPI_fasta/promoter11646.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer439.fa -db EPI_fasta/promoter11772.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer439.fa -db EPI_fasta/promoter11773.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer439.fa -db EPI_fasta/promoter11774.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer439.fa -db EPI_fasta/promoter11775.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer439.fa -db EPI_fasta/promoter11776.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer439.fa -db EPI_fasta/promoter11777.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer439.fa -db EPI_fasta/promoter11778.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer455.fa -db EPI_fasta/promoter12031.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer455.fa -db EPI_fasta/promoter12032.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer455.fa -db EPI_fasta/promoter12033.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer455.fa -db EPI_fasta/promoter12034.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer455.fa -db EPI_fasta/promoter12035.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer455.fa -db EPI_fasta/promoter12036.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer478.fa -db EPI_fasta/promoter12464.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer478.fa -db EPI_fasta/promoter12465.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer478.fa -db EPI_fasta/promoter12466.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer478.fa -db EPI_fasta/promoter12467.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer478.fa -db EPI_fasta/promoter12468.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer478.fa -db EPI_fasta/promoter12469.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer478.fa -db EPI_fasta/promoter12470.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer479.fa -db EPI_fasta/promoter12601.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer479.fa -db EPI_fasta/promoter12602.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12692.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12693.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12694.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12695.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12696.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12697.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12698.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12699.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12700.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12701.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12702.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer481.fa -db EPI_fasta/promoter12703.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer491.fa -db EPI_fasta/promoter12954.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13225.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13226.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13227.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13228.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13229.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13230.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13231.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13232.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13233.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13234.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer500.fa -db EPI_fasta/promoter13235.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer523.fa -db EPI_fasta/promoter13853.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer523.fa -db EPI_fasta/promoter13854.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer523.fa -db EPI_fasta/promoter13855.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer524.fa -db EPI_fasta/promoter13853.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer524.fa -db EPI_fasta/promoter13854.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer524.fa -db EPI_fasta/promoter13855.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14700.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14701.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14702.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14703.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14704.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14705.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14706.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14707.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14708.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14709.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer538.fa -db EPI_fasta/promoter14710.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer544.fa -db EPI_fasta/promoter16303.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer544.fa -db EPI_fasta/promoter16304.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer544.fa -db EPI_fasta/promoter16305.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer548.fa -db EPI_fasta/promoter16380.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer554.fa -db EPI_fasta/promoter16589.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer554.fa -db EPI_fasta/promoter16590.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer554.fa -db EPI_fasta/promoter16591.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer554.fa -db EPI_fasta/promoter16592.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer554.fa -db EPI_fasta/promoter16593.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer555.fa -db EPI_fasta/promoter16625.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer556.fa -db EPI_fasta/promoter16637.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer556.fa -db EPI_fasta/promoter16638.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer556.fa -db EPI_fasta/promoter16639.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer556.fa -db EPI_fasta/promoter16640.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer556.fa -db EPI_fasta/promoter16641.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer556.fa -db EPI_fasta/promoter16642.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer556.fa -db EPI_fasta/promoter16643.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer556.fa -db EPI_fasta/promoter16644.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer563.fa -db EPI_fasta/promoter16816.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer563.fa -db EPI_fasta/promoter16817.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer564.fa -db EPI_fasta/promoter16816.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer564.fa -db EPI_fasta/promoter16817.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer568.fa -db EPI_fasta/promoter16883.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer576.fa -db EPI_fasta/promoter17036.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer576.fa -db EPI_fasta/promoter17037.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer576.fa -db EPI_fasta/promoter17038.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer576.fa -db EPI_fasta/promoter17039.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer576.fa -db EPI_fasta/promoter17040.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer576.fa -db EPI_fasta/promoter17041.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer577.fa -db EPI_fasta/promoter17036.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer577.fa -db EPI_fasta/promoter17037.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer577.fa -db EPI_fasta/promoter17038.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer577.fa -db EPI_fasta/promoter17039.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer577.fa -db EPI_fasta/promoter17040.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer577.fa -db EPI_fasta/promoter17041.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer592.fa -db EPI_fasta/promoter17250.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer595.fa -db EPI_fasta/promoter17425.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer595.fa -db EPI_fasta/promoter17426.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer595.fa -db EPI_fasta/promoter17427.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer595.fa -db EPI_fasta/promoter17428.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer595.fa -db EPI_fasta/promoter17429.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer595.fa -db EPI_fasta/promoter17430.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer595.fa -db EPI_fasta/promoter17431.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer595.fa -db EPI_fasta/promoter17432.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer596.fa -db EPI_fasta/promoter17481.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer596.fa -db EPI_fasta/promoter17482.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer596.fa -db EPI_fasta/promoter17483.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer596.fa -db EPI_fasta/promoter17484.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer596.fa -db EPI_fasta/promoter17485.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer596.fa -db EPI_fasta/promoter17486.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer596.fa -db EPI_fasta/promoter17487.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer597.fa -db EPI_fasta/promoter17481.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer597.fa -db EPI_fasta/promoter17482.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer597.fa -db EPI_fasta/promoter17483.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer597.fa -db EPI_fasta/promoter17484.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer597.fa -db EPI_fasta/promoter17485.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer597.fa -db EPI_fasta/promoter17486.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer597.fa -db EPI_fasta/promoter17487.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer598.fa -db EPI_fasta/promoter17494.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer598.fa -db EPI_fasta/promoter17495.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer598.fa -db EPI_fasta/promoter17496.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer598.fa -db EPI_fasta/promoter17497.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer598.fa -db EPI_fasta/promoter17498.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer602.fa -db EPI_fasta/promoter17588.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer602.fa -db EPI_fasta/promoter17589.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer602.fa -db EPI_fasta/promoter17590.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer602.fa -db EPI_fasta/promoter17591.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer606.fa -db EPI_fasta/promoter17636.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer606.fa -db EPI_fasta/promoter17637.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer607.fa -db EPI_fasta/promoter17636.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer607.fa -db EPI_fasta/promoter17637.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer608.fa -db EPI_fasta/promoter17636.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer608.fa -db EPI_fasta/promoter17637.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer609.fa -db EPI_fasta/promoter17638.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer610.fa -db EPI_fasta/promoter17638.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer611.fa -db EPI_fasta/promoter17638.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer612.fa -db EPI_fasta/promoter17638.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer613.fa -db EPI_fasta/promoter17638.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer627.fa -db EPI_fasta/promoter18083.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer627.fa -db EPI_fasta/promoter18084.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer627.fa -db EPI_fasta/promoter18085.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer627.fa -db EPI_fasta/promoter18086.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer627.fa -db EPI_fasta/promoter18087.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer627.fa -db EPI_fasta/promoter18088.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer627.fa -db EPI_fasta/promoter18089.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer628.fa -db EPI_fasta/promoter18083.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer628.fa -db EPI_fasta/promoter18084.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer628.fa -db EPI_fasta/promoter18085.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer628.fa -db EPI_fasta/promoter18086.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer628.fa -db EPI_fasta/promoter18087.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer628.fa -db EPI_fasta/promoter18088.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer628.fa -db EPI_fasta/promoter18089.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer630.fa -db EPI_fasta/promoter18106.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer630.fa -db EPI_fasta/promoter18107.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer630.fa -db EPI_fasta/promoter18108.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer630.fa -db EPI_fasta/promoter18109.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer630.fa -db EPI_fasta/promoter18110.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer630.fa -db EPI_fasta/promoter18111.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer636.fa -db EPI_fasta/promoter18869.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer636.fa -db EPI_fasta/promoter18870.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer647.fa -db EPI_fasta/promoter19001.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer647.fa -db EPI_fasta/promoter19002.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer647.fa -db EPI_fasta/promoter19003.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer649.fa -db EPI_fasta/promoter19062.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer649.fa -db EPI_fasta/promoter19063.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer649.fa -db EPI_fasta/promoter19064.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer650.fa -db EPI_fasta/promoter19062.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer650.fa -db EPI_fasta/promoter19063.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer650.fa -db EPI_fasta/promoter19064.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer652.fa -db EPI_fasta/promoter19119.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer652.fa -db EPI_fasta/promoter19120.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer652.fa -db EPI_fasta/promoter19121.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer652.fa -db EPI_fasta/promoter19122.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer653.fa -db EPI_fasta/promoter19119.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer653.fa -db EPI_fasta/promoter19120.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer653.fa -db EPI_fasta/promoter19121.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer653.fa -db EPI_fasta/promoter19122.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer654.fa -db EPI_fasta/promoter19295.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer658.fa -db EPI_fasta/promoter19309.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer658.fa -db EPI_fasta/promoter19310.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer658.fa -db EPI_fasta/promoter19311.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer658.fa -db EPI_fasta/promoter19312.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19460.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19461.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19462.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19463.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19464.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19465.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19466.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19467.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19468.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19469.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer665.fa -db EPI_fasta/promoter19470.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19460.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19461.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19462.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19463.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19464.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19465.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19466.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19467.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19468.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19469.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer666.fa -db EPI_fasta/promoter19470.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer668.fa -db EPI_fasta/promoter19500.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer668.fa -db EPI_fasta/promoter19501.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer668.fa -db EPI_fasta/promoter19502.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer668.fa -db EPI_fasta/promoter19503.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer668.fa -db EPI_fasta/promoter19504.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer670.fa -db EPI_fasta/promoter15004.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer670.fa -db EPI_fasta/promoter15005.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer670.fa -db EPI_fasta/promoter15006.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer671.fa -db EPI_fasta/promoter15004.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer671.fa -db EPI_fasta/promoter15005.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer671.fa -db EPI_fasta/promoter15006.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer672.fa -db EPI_fasta/promoter15004.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer672.fa -db EPI_fasta/promoter15005.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer672.fa -db EPI_fasta/promoter15006.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15299.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15300.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15301.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15302.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15303.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15304.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15305.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15306.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15307.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer680.fa -db EPI_fasta/promoter15308.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer691.fa -db EPI_fasta/promoter15397.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer691.fa -db EPI_fasta/promoter15398.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer691.fa -db EPI_fasta/promoter15399.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer691.fa -db EPI_fasta/promoter15400.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer691.fa -db EPI_fasta/promoter15401.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer691.fa -db EPI_fasta/promoter15402.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer691.fa -db EPI_fasta/promoter15403.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer692.fa -db EPI_fasta/promoter15410.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer692.fa -db EPI_fasta/promoter15411.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer693.fa -db EPI_fasta/promoter15430.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer693.fa -db EPI_fasta/promoter15431.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer693.fa -db EPI_fasta/promoter15432.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer696.fa -db EPI_fasta/promoter15438.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer696.fa -db EPI_fasta/promoter15439.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer697.fa -db EPI_fasta/promoter15438.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer697.fa -db EPI_fasta/promoter15439.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18284.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18285.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18286.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18287.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18288.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18289.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18290.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18291.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18292.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18293.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18294.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18295.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer705.fa -db EPI_fasta/promoter18296.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer719.fa -db EPI_fasta/promoter18532.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer719.fa -db EPI_fasta/promoter18533.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer719.fa -db EPI_fasta/promoter18534.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer719.fa -db EPI_fasta/promoter18535.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer755.fa -db EPI_fasta/promoter19826.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer755.fa -db EPI_fasta/promoter19827.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer755.fa -db EPI_fasta/promoter19828.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer758.fa -db EPI_fasta/promoter19887.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer758.fa -db EPI_fasta/promoter19888.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer758.fa -db EPI_fasta/promoter19889.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer758.fa -db EPI_fasta/promoter19890.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer759.fa -db EPI_fasta/promoter19887.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer759.fa -db EPI_fasta/promoter19888.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer759.fa -db EPI_fasta/promoter19889.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer759.fa -db EPI_fasta/promoter19890.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer763.fa -db EPI_fasta/promoter19964.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer763.fa -db EPI_fasta/promoter19965.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer763.fa -db EPI_fasta/promoter19966.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer763.fa -db EPI_fasta/promoter19967.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer763.fa -db EPI_fasta/promoter19968.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer764.fa -db EPI_fasta/promoter19964.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer764.fa -db EPI_fasta/promoter19965.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer764.fa -db EPI_fasta/promoter19966.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer764.fa -db EPI_fasta/promoter19967.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer764.fa -db EPI_fasta/promoter19968.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer765.fa -db EPI_fasta/promoter19964.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer765.fa -db EPI_fasta/promoter19965.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer765.fa -db EPI_fasta/promoter19966.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer765.fa -db EPI_fasta/promoter19967.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer765.fa -db EPI_fasta/promoter19968.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20349.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20350.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20351.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20352.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20353.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20354.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20355.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20356.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20357.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20358.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20359.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20360.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20361.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20362.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20363.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer776.fa -db EPI_fasta/promoter20364.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer777.fa -db EPI_fasta/promoter20376.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer777.fa -db EPI_fasta/promoter20377.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer777.fa -db EPI_fasta/promoter20378.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer777.fa -db EPI_fasta/promoter20379.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer777.fa -db EPI_fasta/promoter20380.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer779.fa -db EPI_fasta/promoter20459.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer792.fa -db EPI_fasta/promoter20896.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer792.fa -db EPI_fasta/promoter20897.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer792.fa -db EPI_fasta/promoter20898.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer792.fa -db EPI_fasta/promoter20899.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer792.fa -db EPI_fasta/promoter20900.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer793.fa -db EPI_fasta/promoter20896.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer793.fa -db EPI_fasta/promoter20897.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer793.fa -db EPI_fasta/promoter20898.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer793.fa -db EPI_fasta/promoter20899.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer793.fa -db EPI_fasta/promoter20900.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer794.fa -db EPI_fasta/promoter20896.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer794.fa -db EPI_fasta/promoter20897.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer794.fa -db EPI_fasta/promoter20898.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer794.fa -db EPI_fasta/promoter20899.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer794.fa -db EPI_fasta/promoter20900.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer795.fa -db EPI_fasta/promoter20919.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer799.fa -db EPI_fasta/promoter21030.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer799.fa -db EPI_fasta/promoter21031.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer799.fa -db EPI_fasta/promoter21032.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer827.fa -db EPI_fasta/promoter15993.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer827.fa -db EPI_fasta/promoter15994.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer827.fa -db EPI_fasta/promoter15995.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer827.fa -db EPI_fasta/promoter15996.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer827.fa -db EPI_fasta/promoter15997.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer827.fa -db EPI_fasta/promoter15998.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer827.fa -db EPI_fasta/promoter15999.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer828.fa -db EPI_fasta/promoter16014.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
