bash random_EPI_blast_11.sh &
bash random_EPI_blast_37.sh &
bash random_EPI_blast_30.sh &
bash random_EPI_blast_25.sh &
bash random_EPI_blast_32.sh &
bash random_EPI_blast_1.sh &
bash random_EPI_blast_27.sh &
bash random_EPI_blast_10.sh &
bash random_EPI_blast_34.sh &
bash random_EPI_blast_29.sh &
bash random_EPI_blast_44.sh &
bash random_EPI_blast_5.sh &
bash random_EPI_blast_12.sh &
bash random_EPI_blast_35.sh &
bash random_EPI_blast_21.sh &
bash random_EPI_blast_9.sh &
bash random_EPI_blast_31.sh &
bash random_EPI_blast_40.sh &
bash random_EPI_blast_13.sh &
bash random_EPI_blast_28.sh &
bash random_EPI_blast_24.sh &
bash random_EPI_blast_4.sh &
bash random_EPI_blast_7.sh &
bash random_EPI_blast_49.sh &
bash random_EPI_blast_43.sh &
bash random_EPI_blast_17.sh &
bash random_EPI_blast_23.sh &
bash random_EPI_blast_22.sh &
bash random_EPI_blast_0.sh &
bash random_EPI_blast_36.sh &
bash random_EPI_blast_14.sh &
bash random_EPI_blast_16.sh &
bash random_EPI_blast_39.sh &
bash random_EPI_blast_42.sh &
bash random_EPI_blast_45.sh &
bash random_EPI_blast_41.sh &
bash random_EPI_blast_15.sh &
bash random_EPI_blast_47.sh &
bash random_EPI_blast_20.sh &
bash random_EPI_blast_48.sh &
bash random_EPI_blast_38.sh &
bash random_EPI_blast_46.sh &
bash random_EPI_blast_18.sh &
bash random_EPI_blast_19.sh &
bash random_EPI_blast_33.sh &
bash random_EPI_blast_6.sh &
bash random_EPI_blast_8.sh &
bash random_EPI_blast_2.sh &
bash random_EPI_blast_3.sh &
bash random_EPI_blast_26.sh &
wait
