makeblastdb -in EPI_fasta/promoter4869.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7394.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9995.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter788.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10000.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4513.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10960.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10004.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7403.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10003.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9499.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9997.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12001.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4870.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4511.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4509.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter787.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10957.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9991.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9993.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10007.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4866.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10962.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4505.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9990.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7956.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7392.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7395.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7399.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter789.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10006.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4506.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10005.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7398.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4504.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10966.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4868.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10958.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10002.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9996.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4510.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10964.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4437.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10963.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4508.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7390.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9502.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4867.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter786.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7402.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4512.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4503.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7388.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7397.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter790.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7391.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7396.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9988.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11998.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4507.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7404.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7955.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12002.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7401.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter12000.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10008.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter11999.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9999.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10965.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10961.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10959.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter9998.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter4502.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7393.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter10001.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7400.fa -dbtype nucl >> EPI_makedb.log
makeblastdb -in EPI_fasta/promoter7954.fa -dbtype nucl >> EPI_makedb.log
