blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter786.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter787.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter788.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter789.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer0.fa -db EPI_fasta/promoter790.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7388.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7390.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7391.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7392.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7393.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7394.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7395.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7396.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7397.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7398.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7399.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7400.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7401.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7402.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7403.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer1.fa -db EPI_fasta/promoter7404.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7388.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7390.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7391.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7392.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7393.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7394.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7395.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7396.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7397.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7398.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7399.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7400.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7401.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7402.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer3.fa -db EPI_fasta/promoter7403.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer4.fa -db EPI_fasta/promoter4437.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer6.fa -db EPI_fasta/promoter9499.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer6.fa -db EPI_fasta/promoter9502.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10957.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10958.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10959.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10960.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10961.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10962.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10963.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10964.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10965.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer7.fa -db EPI_fasta/promoter10966.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer10.fa -db EPI_fasta/promoter11998.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer10.fa -db EPI_fasta/promoter11999.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer10.fa -db EPI_fasta/promoter12000.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer10.fa -db EPI_fasta/promoter12001.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer10.fa -db EPI_fasta/promoter12002.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer11.fa -db EPI_fasta/promoter7954.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer11.fa -db EPI_fasta/promoter7955.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer11.fa -db EPI_fasta/promoter7956.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4502.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4503.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4504.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4505.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4506.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4507.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4508.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4509.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4510.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4511.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4512.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer12.fa -db EPI_fasta/promoter4513.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer14.fa -db EPI_fasta/promoter4866.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer14.fa -db EPI_fasta/promoter4867.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer14.fa -db EPI_fasta/promoter4868.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer14.fa -db EPI_fasta/promoter4869.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer14.fa -db EPI_fasta/promoter4870.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter9988.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter9990.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter9991.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter9993.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter9995.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter9996.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter9997.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter9998.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter9999.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter10000.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter10001.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter10002.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter10003.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter10004.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter10005.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter10006.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter10007.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
blastn -task blastn -query EPI_fasta/enhancer15.fa -db EPI_fasta/promoter10008.fa -outfmt 6 -evalue 1e-4 >> EPI_blastResult.txt
